"fofa":
  "enable": true
  "fofa_email": ""
  "fofa_key": ""
  "fofa_select": "domain=\"%s\" || cert=\"%s\" || host=\"%s\" || cname=\"%s\""

"quake":
  "enable": true
  "quake_key": ""
  "quake_select": "domain: %s || cert: %s || hostname: %s"

"zoomeye":
  "enable": true
  "zoomeye_key": ""

"hunter":
  "enable": true
  "hunter_username": ""
  "hunter_key": ""
  "hunter_select": "domain=\"%s\"||cert=\"%s\""


  